// Store Action Types 
export const GET_USERS = 'GET_USERS';
export const SHOW_FIRSTDATA_ALL = 'SHOW_FIRSTDATA_ALL';
export const LOGIN = 'LOGIN';
export const SET_ENGAGEMENTS = 'SET_ENGAGEMENTS';
export const SET_PLAYER_SUMMARY = 'SET_PLAYER_SUMMARY';
export const SET_ENGAGEMENT_SUMMARY='SET_ENGAGEMENT_SUMMARY';
export const SET_ENGAGEMENTS_RULE_AMOUNTS='SET_ENGAGEMENTS_RULE_AMOUNTS';
export const SELECTED_ENGAGEMENT = 'SELECTED_ENGAGEMENT';
export const GET_GAME_DETAIL = 'GET_GAME_DETAIL';
export const GET_USER_REWARDS = 'GET_USER_REWARDS';
export const GET_LEADERBOARD = 'GET_LEADERBOARD';
export const GET_LEADERBOARD_OTHERS_PLAYING = 'GET_LEADERBOARD_OTHERS_PLAYING';
export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_STATUS = 'GET_STATUS';

export const SET_CUSTOMER_SAVINGS = 'SET_CUSTOMER_SAVINGS';
export const SET_TOP_CUSTOMER_SAVINGS = 'SET_TOP_CUSTOMER_SAVINGS';
export const SET_CUSTOMER_DETAILS = 'SET_CUSTOMER_DETAILS';
export const SET_TOURNAMENTS = 'SET_TOURNAMENTS';

export const SET_OPEN_ALERT_DIALOG='SET_OPEN_ALERT_DIALOG';
export const SET_SHOW_LOADER='SET_SHOW_LOADER';


// Application URL's 
export const GET_USERS_URL = '/api/users?page=';
export const LOGIN_URL = '';
export const GET_GAME_DETAIL_URL = '';
export const GET_USER_REWARDS_URL = '';
export const GET_LEADERBOARD_URL = '';
export const GET_LEADERBOARD_OTHERS_PLAYING_URL = '';
export const GET_TRANSACTION_HISTORY_URL = '';